# This is a basic workflow to help you get started with Actions

name: Sample Book App Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
   

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Step description
        run: echo "Building docker image.."
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Step description
        run: echo "Deployment triggered on dev environment"
  api-integration-tests-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Step description
        run: echo "API tests triggered on DEV environment.."
  deploy-stg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Step description
        run: echo "Deployment triggered on stg environment"
  api-integration-tests-stg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Step description
        run: echo "API tests triggered on STG environment.."
  deploy-prd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Step description
        run: echo "Deployment triggered on prd environment"
  api-integration-tests-prd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Step description
        run: echo "API tests triggered on PRD environment.."